### ISSUE TITLE
java.lang.ClassCastException

### ISSUE THREAD

**Issue by perryBunn** [perryBunn/COMP1210#11]
```
Exception in thread "main" java.lang.ClassCastException: Pie cannot be cast to java.lang.Comparable
        at java.util.ComparableTimSort.countRunAndMakeAscending(Unknown Source)
        at java.util.ComparableTimSort.sort(Unknown Source)
        at java.util.Arrays.sort(Unknown Source)
        at BakedItemList.generateReportByClass(BakedItemList.java:235)
        at BakeryPart2.main(BakeryPart2.java:19)
```

Pie object can can not be compared in the generateReportByClass() method

**Comment by perryBunn** [comment]
resolved: did not implement Comparator<BakedItem> in BakedItem class.
